name: CI

on:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${{github.event}}
          echo ${{github.event.client_payload}}
          echo ${{github.event.client_payload.commit_sha}}
          echo ${{github.event.client_payload.env}}


