name: CI

on:
  repository_dispatch:
    types: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo github event client payload parameters
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${{github.event.client_payload.commit_sha}}
          echo ${{toJSON(github.event)}}
  
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create dummy commit
        run: |
          regions=${{github.event.client_payload.regions}}
          commit_sha=${{github.event.client_payload.commit_sha}}
          env=${{github.event.client_payload.env}}
          
          for region in ${regions[*]}
          do
            echo "${region}"
          done
          
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
          echo "Deploy to ${env} - ${regions[*]} - ${commit_sha}" > tag.txt
          
          git add .
          git commit -m ":rocket: Deploy to ${env} - ${regions}"
          git push


