name: CI

on:
  repository_dispatch:
    types: [deploy]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Echo github event client payload parameters
        run: |
          python3 ./scripts/update_values.py \
            --env ${{github.event.client_payload.env}} \
            --regions "${{github.event.client_payload.regions}}" \
            --tag ${{github.event.client_payload.commit_sha}}
            
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          
          git add .
          git commit -m ":rocket: Deploy to ${env} - ${regions}"
          git push

